# Generated by Django 5.2.5 on 2025-09-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('palabras_clave', models.CharField(blank=True, max_length=250, null=True)),
                ('imagen', models.URLField(help_text='URL de la imagen del videojuego')),
                ('link_steam', models.URLField(help_text='Enlace a la página de Steam')),
            ],
        ),
    ]
